version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            # serverless-plugin-optimize/.git was causing problems for npm install 
            rm -rf node_modules/serverless-plugin-optimize/.git
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
        
      # run tests!
      - run: 
          name: Run tests with coverage
          command: npm test --coverage

      - run:
          name: Deploy application
          command: |
            echo "APPLICATION_VER=${CIRCLE_SHA1:0:7}-${CIRCLE_BUILD_NUM}" >> .env.production
            cat .env.production
            ls
            echo ${CIRCLE_SHA1:0:7}
            npm run deploy:prod
